site_name: adfwer的笔记
theme:
  name: "material"
  features:
    - navigation.tabs
    - navigation.tabs.sticky
  palette:
      primary: "black"
      accent: "deep orange"
  language: "zh"
  icon:
  admonition:
    <type>: <icon>

markdown_extensions:
  - toc:
      permalink: True
  - footnotes
  - tables
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true
  - markdown_checklist.extension

plugins:
  - mkdocs-jupyter:
      ignore_h1_titles: True
      kernel_name: python3
      ignore: ["*.py"]
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
