site_name: adfwer的笔记

repo_name: adfwer233/adfwerNote
repo_url: https://github.com/adfwer233/adfwerNote

theme:
  name: "material"
  features:
    - content.code.annotate
    - navigation.indexes
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate
  include_search_page: false
  search_index_only: true
  palette:
    - scheme: default
      primary: cyan
      accent: cyan
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - scheme: slate
      primary: black
      accent: black
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.png
  language: "zh"

markdown_extensions:
  - toc:
      permalink: True
  - footnotes
  - tables
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true
  - markdown_checklist.extension

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/adfwer233

plugins:
  - mkdocs-jupyter:
      ignore_h1_titles: True
      kernel_name: python3
      ignore: ["*.py"]
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
